version: '3.8'
services:
  student-service:
    build: ./student-service/
    image: student-service
    container_name: student-service
    ports:
      - "8080:8080"
    networks:
      - school-network

  catalog-service:
    build: ./catalog-service/
    image: catalog-service
    container_name: catalog-service
    ports:
      - "8081:8081"
    networks:
      - school-network

  fee-collection-service:
    build: ./fee-collection-service/
    image: fee-collection-service
    container_name: fee-collection-service
    ports:
      - "8082:8082"
    networks:
      - school-network
  
networks:
  school-network:
    driver: bridge