spring:
  application:
    name: transaction-service

server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

integration:
  catalog-service:
    base-url: http://${host.docker.internal:localhost}:8081/
  student-service:
    base-url: http://${host.docker.internal:localhost}:8080/
